### ISSUE TITLE
rendering

### ISSUE THREAD

**Issue by zhansingsong** [zhansingsong/singsong#1]
http://www.singsong.me/articles/5bc04ef6bdd9429dc36310b3

**Comment by zhansingsong** [comment]
哈哈哈😆

**Comment by Ceelog** [comment]
Hello World

**Comment by zhansingsong** [comment]
### markdown-code-style
- js
```js
import profile from './modules/profile';
import project from './modules/project';

profile.init();
project.init();
```
- css
```css
.app {
  position: relative;
  min-height: 100%;
  box-sizing: border-box;
  padding-bottom: 140px;
}
```
